name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade Flask
          pip install --upgrade --force-reinstall Jinja2

      - name: Test Application
        run: |
          # Add your test commands here

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade Flask
          pip install --upgrade --force-reinstall Jinja2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: vminstance-414214

      - name: Upload to Cloud Storage
        run: |
          gsutil cp main.py gs://demo-cicd/main.py


      - name: Deploy to App Engine from Cloud Storage
        run: |
          gcloud app deploy --quiet  gs://demo-cicd/main.py

